/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package me.geales.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class HeaderRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7138513701023169953L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HeaderRecord\",\"namespace\":\"me.geales.avro\",\"fields\":[{\"name\":\"appID\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<HeaderRecord> ENCODER =
      new BinaryMessageEncoder<HeaderRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<HeaderRecord> DECODER =
      new BinaryMessageDecoder<HeaderRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<HeaderRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<HeaderRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<HeaderRecord>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this HeaderRecord to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a HeaderRecord from a ByteBuffer. */
  public static HeaderRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence appID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public HeaderRecord() {}

  /**
   * All-args constructor.
   * @param appID The new value for appID
   */
  public HeaderRecord(java.lang.CharSequence appID) {
    this.appID = appID;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return appID;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: appID = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'appID' field.
   * @return The value of the 'appID' field.
   */
  public java.lang.CharSequence getAppID() {
    return appID;
  }

  /**
   * Sets the value of the 'appID' field.
   * @param value the value to set.
   */
  public void setAppID(java.lang.CharSequence value) {
    this.appID = value;
  }

  /**
   * Creates a new HeaderRecord RecordBuilder.
   * @return A new HeaderRecord RecordBuilder
   */
  public static me.geales.avro.HeaderRecord.Builder newBuilder() {
    return new me.geales.avro.HeaderRecord.Builder();
  }

  /**
   * Creates a new HeaderRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new HeaderRecord RecordBuilder
   */
  public static me.geales.avro.HeaderRecord.Builder newBuilder(me.geales.avro.HeaderRecord.Builder other) {
    return new me.geales.avro.HeaderRecord.Builder(other);
  }

  /**
   * Creates a new HeaderRecord RecordBuilder by copying an existing HeaderRecord instance.
   * @param other The existing instance to copy.
   * @return A new HeaderRecord RecordBuilder
   */
  public static me.geales.avro.HeaderRecord.Builder newBuilder(me.geales.avro.HeaderRecord other) {
    return new me.geales.avro.HeaderRecord.Builder(other);
  }

  /**
   * RecordBuilder for HeaderRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HeaderRecord>
    implements org.apache.avro.data.RecordBuilder<HeaderRecord> {

    private java.lang.CharSequence appID;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(me.geales.avro.HeaderRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.appID)) {
        this.appID = data().deepCopy(fields()[0].schema(), other.appID);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing HeaderRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(me.geales.avro.HeaderRecord other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.appID)) {
        this.appID = data().deepCopy(fields()[0].schema(), other.appID);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'appID' field.
      * @return The value.
      */
    public java.lang.CharSequence getAppID() {
      return appID;
    }

    /**
      * Sets the value of the 'appID' field.
      * @param value The value of 'appID'.
      * @return This builder.
      */
    public me.geales.avro.HeaderRecord.Builder setAppID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.appID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'appID' field has been set.
      * @return True if the 'appID' field has been set, false otherwise.
      */
    public boolean hasAppID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'appID' field.
      * @return This builder.
      */
    public me.geales.avro.HeaderRecord.Builder clearAppID() {
      appID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public HeaderRecord build() {
      try {
        HeaderRecord record = new HeaderRecord();
        record.appID = fieldSetFlags()[0] ? this.appID : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<HeaderRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<HeaderRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<HeaderRecord>
    READER$ = (org.apache.avro.io.DatumReader<HeaderRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
